# Generated by Django 4.2.16 on 2025-04-28 09:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Communities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="community",
            name="online_members",
            field=models.ManyToManyField(
                blank=True,
                related_name="online_communities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
