# Generated by Django 4.2.16 on 2025-04-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Communities", "0002_community_online_members"),
    ]

    operations = [
        migrations.AddField(
            model_name="communitymessage",
            name="file_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="communitymessage",
            name="file_size",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
