# Generated by Django 4.2.16 on 2025-04-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Communities", "0003_communitymessage_file_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="communitymessage",
            name="file_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
