# Generated by Django 4.2.16 on 2024-10-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("QueryMate", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="downvote_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="question",
            name="upvote_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
