# Generated by Django 4.2.16 on 2024-10-11 09:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("QueryMate", "0003_answer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="answer",
            old_name="detail",
            new_name="content",
        ),
        migrations.AlterUniqueTogether(
            name="answer",
            unique_together={("user", "question")},
        ),
    ]
