# Generated by Django 4.2.16 on 2024-10-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("QueryMate", "0005_alter_answer_question_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
