# Generated by Django 4.2.16 on 2024-10-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("QueryMate", "0006_review_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="downvote_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="answer",
            name="upvote_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
