# Generated by Django 4.2.16 on 2024-10-27 06:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Chats", "0003_message"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["-created_at"]},
        ),
    ]
