# Generated by Django 4.2.16 on 2025-05-03 05:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Chats", "0005_message_deleted_at_message_is_deleted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="file",
            field=models.FileField(blank=True, upload_to="ChatsFiles/"),
        ),
    ]
