# Generated by Django 4.2.16 on 2025-05-04 06:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Chats", "0006_alter_message_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="like_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="message",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="like_messages", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
