# Generated by Django 4.2.16 on 2025-10-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Chats", "0007_message_like_count_message_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
